minimum_pre_commit_version: 1.21.0
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  # reorder Python imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports

  # format Python code with black
  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-builtin-literals
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/PyCQA/flake8/
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: check-fixmes
        name: check-fixmes
        language: system
        entry: ./.pre-commit-scripts/check-fixme.sh
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: generate-requirements
        name: generate-requirements
        entry: ./.pre-commit-scripts/generate-requirements.sh
        language: system
        files: poetry.lock
        pass_filenames: false
